# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-11 18:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedMiningRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=240)),
                ('requested_by', models.CharField(max_length=240)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinedRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=240)),
                ('requested_by', models.CharField(max_length=240)),
                ('num_pulls', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_closed_merged_pulls', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_closed_unmerged_pulls', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_open_pulls', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at_list', django_mysql.models.ListTextField(models.CharField(max_length=240), size=None)),
                ('closed_at_list', django_mysql.models.ListTextField(models.CharField(max_length=240), size=None)),
                ('merged_at_list', django_mysql.models.ListTextField(models.CharField(max_length=240), size=None)),
                ('num_newcomer_labels', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiningRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=240)),
                ('requested_by', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254)),
                ('send_email', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=240)),
                ('owner', models.CharField(max_length=240)),
            ],
        ),
    ]
