# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='miningrequest',
            name='repo_name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterUniqueTogether(
            name='miningrequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='miningrequest',
            name='pull_request_number',
        ),
    ]
