# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20190201_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=240)),
                ('owner', models.CharField(max_length=240)),
            ],
        ),
    ]
