# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-02 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0003_auto_20181202_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='miningRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=120)),
                ('pull_request_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
