# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0004_miningrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningrequest',
            name='pull_request_number',
            field=models.IntegerField(unique=True),
        ),
    ]
