# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0005_auto_20181202_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningrequest',
            name='pull_request_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='miningrequest',
            unique_together=set([('repo_name', 'pull_request_number')]),
        ),
    ]
